name: meow_meet
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  firebase_storage: ^12.1.0
  firebase_database: ^11.0.4
  google_sign_in: ^6.2.1
  sign_in_button: ^3.2.0
  cloud_firestore: ^5.0.2
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  geocoding: ^2.0.0
  provider: ^6.1.2
  google_fonts: ^4.0.3
  cupertino_icons: ^1.0.2
  country_picker: ^2.0.26
  profanity_filter: ^2.0.0
  flag: ^7.0.0
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.2
  google_mlkit_image_labeling: ^0.12.0
  flutter_nude_checker: ^1.0.1
  http: ^1.2.1
  intl: ^0.19.0
  image_cropper: ^7.1.0
  path_provider: ^2.1.3
  settings_ui: ^2.0.2
  country_codes_info: ^0.0.7
  dotenv: ^4.2.0
  buttons_tabbar: ^1.3.12
  flutter_localized_locales: ^2.0.5
  shared_preferences: ^2.2.3
  navigation_view: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/map_style.json
    - assets/images/logo.png
    - assets/images/default_profile.png
    - assets/images/male.png
    - assets/images/female.png
    - assets/images/other.png
    - assets/countries.json
    - assets/images/google_logo.png
    - assets/service_account.json
    - assets/.env
    - assets/loading_gifs/cat_eating_main.gif
